Algoritmo "lacorepita"
//  
//  
// Descrição   :
// Autor(a)    : Brenda Sena
// Data atual  : 18/08/2020
Var
// Seção de Declarações das variáveis 
x : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
----------------------------escreva("LACO PARA REPITA")---------------------------------

repita
	escreval (x)
	x<- x + 1
ate (x>10)

Fimalgoritmo