Algoritmo "lacoencremento"
//  
//  
// Descrição   :
// Autor(a)    : Brenda Sena
// Data atual  : 18/08/2020
Var
// Seção de Declarações das variáveis 
x : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
--------------------------escreva("LACO PARA INCREMENTO")--------------------------

para x de 1 ate 20 passo 1 faca
	escreval (x)
fimpara

Fimalgoritmo