Algoritmo "lacodecremento"
//  
//  
// Descrição   :
// Autor(a)    : Brenda Sena
// Data atual  : 18/08/2020
Var
// Seção de Declarações das variáveis 
x : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
-------------------------escreva("LACO PARA DECREMENTO")--------------------------

para x de 20 ate 1 passo -1 faca
	escreval (x)
fimpara

Fimalgoritmo