Algoritmo "parouimpar"
//  
//  
// Descrição   : digitar o valor e informar se é par ou ímpar
// Autor(a)    : Brenda Sena
// Data atual  : 07/06/2020
Var
// Seção de Declarações das variáveis 
num: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um valor:")
leia (num)

se  (num mod 2)= 0 entao
    escreval ("Par:")
    
senao
     escreval ("Ímpar:")

fimse

Fimalgoritmo